fix(start script): prevent an empty '2' file to be created and write message to stderr like expected

diff --git a/bin/pipeline_start b/bin/pipeline_start
--- a/bin/pipeline_start
+++ b/bin/pipeline_start
@@ -11,7 +11,7 @@ test -d ${LOG_DIR} || mkdir -p ${LOG_DIR}
 test -d ${PROC_DIR} || mkdir -p ${PROC_DIR}
 
 if [ -f ${PID_FRONT_FILE} ] ; then
-    >2& echo "Pids File ${PID_FRONT_FILE} already exists. Process is probably already running. Can't continue"
+    >&2 echo "Pids File ${PID_FRONT_FILE} already exists. Process is probably already running. Can't continue"
     exit 1;
 fi
 
